# FOR DC32
# z position is relative to the detector center
# Center wire id is zero-origin.
# Angle is defined so that the coordinate system is the right-handed system.
#
# The angle of axis of each plane to the horizontal axis.

- x1: #X1
    z:         +8.4
    nWire:    &nwire  16
    cellSize: &cell   5.
    angle:    &xangle 0.
    center:    8

- x2: #X1'
    z:         +3.45
    nWire:    *nwire
    cellSize: *cell
    angle:    *xangle
    center:    7.5

- y1: #Y1
    z:         -1.5
    nWire:    *nwire
    cellSize: *cell
    angle:    &yangle 90.
    center:    8

- y2: #Y1'
    z:         -6.45
    nWire:    *nwire
    cellSize: *cell
    angle:    *yangle
    center:    7.5

