#
# z position is relative to the detector center
# Center wire id is zero-origin.
# Angle is defined so that the coordinate system is the right-handed system.
#
# The angle of axis of each plane to the horizontal axis.

- x1: #X1
    z:         +7.5
    nWire:    &nwire  16
    cellSize: &cell   5.
    angle:    &xangle 0.
    center:    7.75

- x2: #X1'
    z:         +2.7
    nWire:    *nwire
    cellSize: *cell
    angle:    *xangle
    center:    8.25

- y1: #Y1
    z:         -2.1
    nWire:    *nwire
    cellSize: *cell
    angle:    &yangle 90.
    center:    7.75

- y2: #Y1'
    z:         -6.9
    nWire:    *nwire
    cellSize: *cell
    angle:    *yangle
    center:    8.25

